### ISSUE TITLE
File not found: network/wwd_network_constants.h

### ISSUE THREAD

**Issue by x893** [AriZuu/emw-meter#1]
Hi,
good project. Can you say about file network/wwd_network_constants.h

emw-meter/config/lwipopts.h:34:10: fatal error: network/wwd_network_constants.h: No such file or directory
 #include "network/wwd_network_constants.h"

Thanks in advance

**Comment by AriZuu** [comment]
That file is part of Cypress WICED SDK and obtaining it requires manual steps as it is not freely distributable (requires registration although it is free of charge). See instructions in https://github.com/AriZuu/wiced-driver. Remember the patches also (both MXCHIP and mine), they are important, things won't work without them.

**Comment by x893** [comment]
May be you can add to repository all files (WICED-SDK-6.2 and others) ?
For easy clone and run make :)

**Comment by AriZuu** [comment]
Unfortunately no, I cannot. WICED-SDK license doesn't allow it. You must get it yourself from Cypress.

**Comment by x893** [comment]
OK, i download and install 6.2.1 but compiler can't find some files. rtos.h for example.
During compile wiced-driver repo.
Need a time for resolve.

Thanks for projects.

**Comment by AriZuu** [comment]
Hmm, it compiles fine for me:

% cd emw-meter
% gmake
gmake -C /usr/home/ari/my-development/embedded/emw-meter/../cmsis-ports/stm32f4xx -f Makefile --no-print-directory all OLIBNAME=stm32f4xx
gmake -f Makefile.lib all
gmake[2]: Kohteelle ”all” ei tarvitse tehdä mitään.
gmake -C ../picoos-lwip -f Makefile --no-print-directory all OLIBNAME=picoos-lwip
gmake[1]: Kohteelle ”all” ei tarvitse tehdä mitään.
gmake -C ../wiced-driver -f Makefile --no-print-directory all OLIBNAME=wiced-driver
gmake[1]: Kohteelle ”all” ei tarvitse tehdä mitään.
gmake -C ../eshell -f Makefile --no-print-directory all OLIBNAME=eshell
gmake[1]: Kohteelle ”all” ei tarvitse tehdä mitään.
gmake -C ../picoos-ow -f Makefile --no-print-directory all OLIBNAME=picoos-ow
gmake[1]: Kohteelle ”all” ei tarvitse tehdä mitään.
gmake -C ../potato-bus -f Makefile --no-print-directory all OLIBNAME=potato-bus
gmake[1]: Kohteelle ”all” ei tarvitse tehdä mitään.
gmake -C ../picoos-micro -f Makefile --no-print-directory all OLIBNAME=picoos-micro
gmake[1]: Kohteelle ”all” ei tarvitse tehdä mitään.
gmake -C ../picoos-micro-spiffs -f Makefile --no-print-directory all OLIBNAME=picoos-micro-spiffs
gmake[1]: Kohteelle ”all” ei tarvitse tehdä mitään.
gmake -C ../picoos/ --no-print-directory all OLIBNAME=picoos
gmake[1]: Kohteelle ”all” ei tarvitse tehdä mitään.
arm-none-eabi-gcc -mthumb -L../picoos/ports/cortex-m/boot  -Temw3165.ld -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -Wl,--wrap=malloc,--wrap=free,--wrap=realloc,--wrap=__sfp_lock_acquire,--wrap=__sfp_lock_release,--wrap=fopen -nostartfiles -Wl,-Map,/usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/out/emw-meter.map,--cref,--gc-sections -o/usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/out/emw-meter.elf -Wl,--start-group /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/main.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/startup.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/romfiles.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/sta.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/ap.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/led.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/devtree.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/spibus.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/sensor.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/ssd1306.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/gui.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/ugui.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/potato.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/fonts/BebasNeue_17X34.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/obj/emw-meter/fonts/FMI_weather_34X33.o /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/lib/stm32f4xx.a /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/lib/picoos-lwip.a /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/lib/wiced-driver.a /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/lib/eshell.a /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/lib/picoos-ow.a /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/lib/potato-bus.a /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/lib/picoos-micro.a /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/lib/picoos-micro-spiffs.a -lm /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/lib/picoos.a -lc -Wl,--end-group
arm-none-eabi-size /usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/out/emw-meter.elf
   text	   data	    bss	    dec	    hex	filename
 439200	   2752	  47184	 489136	  776b0	/usr/home/ari/my-development/embedded/emw-meter/bin/cortex-m-rel/out/emw-meter.elf

**Comment by x893** [comment]
I think problem with WICED SDK

make -C ../wiced-driver -f Makefile --no-print-directory all OLIBNAME=wiced-driver
arm-none-eabi-gcc -Wbad-function-cast -Wno-strict-prototypes -Wmissing-prototypes -g -mthumb -fno-common -mcpu=cortex-m4 -ffunction-sections -fdata-sections -Wcast-align -Wall -Wextra -Wshadow -Wpointer-arith -Wno-unused-parameter -Wno-unused-label -Wno-unused-but-set-variable -mfpu=fpv4-sp-d16 -mfloat-abi=hard -Wno-cast-align -Wno-missing-field-initializers -c -o/mnt/f/Downloads/MXCHIP/EMW3165/emw-meter/bin/cortex-m-deb/obj/wiced-driver/WICED-SDK-6.2/WICED/WWD/internal/wwd_wifi.o -I. -I../picoos/inc -I/mnt/f/Downloads/MXCHIP/EMW3165/emw-meter/config -I../picoos/ports/cortex-m -IWICED-SDK-6.2/libraries/utilities/TLV -IWICED-SDK-6.2/libraries/utilities/ring_buffer -IWICED-SDK-6.2/WICED/security/BESL/include -IWICED-SDK-6.2/WICED/platform/GCC -IWICED-SDK-6.2/WICED/platform/MCU/STM32F4xx -IWICED-SDK-6.2/WICED/platform/MCU/ -IWICED-SDK-6.2/WICED/platform/include -IWICED-SDK-6.2/WICED/platform/ARM_CM4 -IWICED-SDK-6.2/WICED/platform/MCU/STM32F4xx/peripherals -IWICED-SDK-6.2/WICED/platform/MCU/STM32F4xx/WAF -IWICED-SDK-6.2/WICED/WWD -IWICED-SDK-6.2/WICED/WWD/include -IWICED-SDK-6.2/WICED/WWD/include/network -IWICED-SDK-6.2/WICED/WWD/internal/bus_protocols/SDIO -IWICED-SDK-6.2/WICED/WWD/internal/chips/43362 -IWICED-SDK-6.2/WICED/WWD/include/RTOS -Iglue -Iglue/ports/cortex-m -IWICED-SDK-6.2/WICED -IWICED-SDK-6.2/platforms/EMW3165 -IWICED-SDK-6.2/include -I/mnt/f/Downloads/MXCHIP/EMW3165/emw-meter/../cmsis-ports/stm32f4xx/../CMSIS/CMSIS/Include -I/mnt/f/Downloads/MXCHIP/EMW3165/emw-meter/../cmsis-ports/stm32f4xx/inc -I../picoos-micro -I../picoos-micro/fat/src -I../picoos-lwip/include -I../picoos-lwip/lwip/src/include -I../picoos-lwip/lwip/src/include/ipv4 -I../picoos-lwip/lwip/src/include/ipv6 -I/mnt/f/Downloads/MXCHIP/EMW3165/emw-meter/../cmsis-ports/stm32f4xx/../CMSIS/CMSIS/Include -I/mnt/f/Downloads/MXCHIP/EMW3165/emw-meter/../cmsis-ports/stm32f4xx/inc -I../picoos-lwip/include -I../picoos-lwip/lwip/src/include -I../picoos-lwip/lwip/src/include/ipv4 -I../picoos-lwip/lwip/src/include/ipv6 -I../wiced-driver/WICED-SDK-6.2/WICED/WWD/include -I../wiced-driver/WICED-SDK-6.2/WICED/WWD/ -I../wiced-driver/WICED-SDK-6.2/WICED/WWD/include/network -I../wiced-driver/WICED-SDK-6.2/WICED/WWD/internal/chips/43362 -I../wiced-driver/WICED-SDK-6.2/WICED/WWD/internal/bus_protocols/SDIO -I../wiced-driver/WICED-SDK-6.2/WICED/platform/include -I../wiced-driver/WICED-SDK-6.2/include -I../wiced-driver/WICED-SDK-6.2/platforms/EMW3165 -I../wiced-driver/glue -I../wiced-driver/glue/ports/cortex-m -I../wiced-driver -I../wiced-driver/WICED-SDK-6.2/WICED/platform/ARM_CM4 -I../picoos/ports/cortex-m/stm32 -DGCC -D_DBG -D_POSPACK -DPICOOS_WORKAROUNDS -DGPIO_LED_NOT_SUPPORTED -DWICED_DISABLE_BOOTLOADER -DWICED_DISABLE_STDIO -DWICED_DISABLE_WATCHDOG -DFIRMWARE_WITH_PMK_CALC_SUPPORT -DWWD_STARTUP_DELAY=10 -DMAX_WATCHDOG_TIMEOUT_SECONDS=22 -DNETWORK_LwIP=1 -DHSE_VALUE=26000000 -DSTM32F411xE -DUSE_STDPERIPH_DRIVER -DPOSNANO WICED-SDK-6.2/WICED/WWD/internal/wwd_wifi.c
In file included from WICED-SDK-6.2/include/wiced_wifi.h:44:0,
                 from WICED-SDK-6.2/WICED/WWD/internal/wwd_wifi.c:61:
WICED-SDK-6.2/include/wiced_rtos.h:47:10: fatal error: rtos.h: No such file or directory
 #include "rtos.h"
          ^~~~~~~~
compilation terminated.

**Comment by AriZuu** [comment]
Looks like haven't applied wiced.patch or there has been a problem when applying it. Check that it applies cleanly.

**Comment by AriZuu** [comment]
If you have problems with patch, it might be a crlf issue. See https://github.com/AriZuu/wiced-driver/issues/1 for possible solutions.

**Comment by AriZuu** [comment]
@x893 did you manage getting wiced-driver to compile ?

**Comment by AriZuu** [comment]
Closing this as it works for me and there has been no feedback. Please reopen if this is still a problem.

**Comment by AriZuu** [comment]
wiced-driver library now has setup_wiced_sdk.sh script which might be helpful when extracting and patching SDK sources.
